### ISSUE TITLE
How to set weight/widths of container components?

### ISSUE THREAD

**Issue by erdalkaraca** [WolframHempel/goldenlayout#2]
If I have a row with two components: how do I tell its container how to seize the components?
For example, the first component should have 30% and the second one 70% of the available width.

Thanks!

**Comment by WolframHempel** [comment]
@erdalkaraca I'm not sure how you ended up in this repo :-) The main goldenlayout website is

https://golden-layout.com/

which has lots of documentation covering both of your questions as well as examples for the scrolling one.  The main repo is https://github.com/deepstreamIO/golden-layout which also has the MIT license.
